za_zakretem_user:
    resource: "@ZaZakretemUserBundle/Resources/config/routing.yml"
    prefix:   /

za_zakretem_models:
    resource: "@ZaZakretemModelsBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
