za_zakretem_game:
    resource: "@ZaZakretemGameBundle/Resources/config/routing.yml"
    prefix:   /

za_zakretem_models:
    resource: "@ZaZakretemModelsBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
