_index:
    path:     /dash
    defaults: { _controller: ZaZakretemGameBundle:Main:index }

show_car:
    path: /showCar/{carId}
    defaults: { _controller: ZaZakretemGameBundle:Auctions:showCar }

buy_car:
    path:     /buyCar/{carId}
    defaults: { _controller: ZaZakretemGameBundle:Auctions:buyCar }

sell_car:
    path:     /sellCar/{carId}
    defaults: { _controller: ZaZakretemGameBundle:Auctions:sellCar }

view_auctions:
    path:     /viewAuctions
    defaults: { _controller: ZaZakretemGameBundle:Auctions:viewAuctions }

view_garage:
    path: /viewGarage
    defaults: { _controller: ZaZakretemGameBundle:Garage:viewGarage }

activate_car:
    path: /activateCar/{playerCarId}
    defaults: { _controller: ZaZakretemGameBundle:Garage:activateCar }

view_track:
  path: /touge/view/{trackId}
  defaults: { _controller: ZaZakretemGameBundle:Touge:viewTrack }

challenge:
  path: /touge/challenge
  defaults: { _controller: ZaZakretemGameBundle:Touge:challengeOpponent }
